from enum import IntEnum
import cassiopeia as cass

champions = cass.get_champions(region="EUW")
champion_id_to_name = {champion.id: champion.name for champion in champions}

class ChampionClass(IntEnum):
    AD_CASTER = 1
    ENCHANTER = 2
    BATTLE_MAGE = 3
    BRUISER = 4
    DIVER = 5
    CONTROL_MAGE = 6
    EARLY_AD_CARRY = 7
    HYPER_CARRY = 8
    JUGGERNAUT = 9
    MELEE_AD_CARRY = 10
    MAGIC_ASSASSIN = 11
    PHYSICAL_ASSASSIN = 12
    PICK_MAGE = 13
    POKE_MAGE = 14
    VANGUARD = 15
    WARDEN = 16


champion_classes = [cc for cc in ChampionClass]
champion_class_lookup = {
    "Aatrox": ChampionClass.BRUISER,
    "Ahri": ChampionClass.PICK_MAGE,
    "Akali": ChampionClass.MAGIC_ASSASSIN,
    "Akshan": ChampionClass.EARLY_AD_CARRY,
    "Alistar": ChampionClass.WARDEN,
    "Anivia": ChampionClass.CONTROL_MAGE,
    "Annie": ChampionClass.PICK_MAGE,
    "Amumu": ChampionClass.VANGUARD,
    "Aphelios": ChampionClass.HYPER_CARRY,
    "Ashe": ChampionClass.EARLY_AD_CARRY,
    "Aurelion Sol": ChampionClass.CONTROL_MAGE,
    "Azir": ChampionClass.HYPER_CARRY,
    "Bard": ChampionClass.VANGUARD,
    "Blitzcrank": ChampionClass.VANGUARD,
    "Brand": ChampionClass.CONTROL_MAGE,
    "Braum": ChampionClass.WARDEN,
    "Caitlyn": ChampionClass.EARLY_AD_CARRY,
    "Camille": ChampionClass.DIVER,
    "Cassiopeia": ChampionClass.BATTLE_MAGE,
    "Cho'Gath": ChampionClass.VANGUARD,
    "Corki": ChampionClass.POKE_MAGE,
    "Darius": ChampionClass.JUGGERNAUT,
    "Diana": ChampionClass.BATTLE_MAGE,
    "Draven": ChampionClass.EARLY_AD_CARRY,
    "Dr. Mundo": ChampionClass.JUGGERNAUT,
    "Ekko": ChampionClass.MAGIC_ASSASSIN,
    "Elise": ChampionClass.MAGIC_ASSASSIN,
    "Evelynn": ChampionClass.MAGIC_ASSASSIN,
    "Ezreal": ChampionClass.AD_CASTER,
    "Fiddlesticks": ChampionClass.BATTLE_MAGE,
    "Fiora": ChampionClass.BRUISER,
    "Fizz": ChampionClass.MAGIC_ASSASSIN,
    "Galio": ChampionClass.BATTLE_MAGE,
    "Gangplank": ChampionClass.AD_CASTER,
    "Garen": ChampionClass.JUGGERNAUT,
    "Gnar": ChampionClass.VANGUARD,
    "Gragas": ChampionClass.BATTLE_MAGE,
    "Graves": ChampionClass.BRUISER,
    "Gwen": ChampionClass.BATTLE_MAGE,
    "Hecarim": ChampionClass.DIVER,
    "Heimerdinger": ChampionClass.CONTROL_MAGE,
    "Illaoi": ChampionClass.JUGGERNAUT,
    "Irelia": ChampionClass.MELEE_AD_CARRY,
    "Ivern": ChampionClass.ENCHANTER,
    "Janna": ChampionClass.ENCHANTER,
    "Jarvan IV": ChampionClass.DIVER,
    "Jax": ChampionClass.BRUISER,
    "Jayce": ChampionClass.AD_CASTER,
    "Jhin": ChampionClass.AD_CASTER,
    "Jinx": ChampionClass.HYPER_CARRY,
    "Kai'Sa": ChampionClass.HYPER_CARRY,
    "Kalista": ChampionClass.EARLY_AD_CARRY,
    "Karma": ChampionClass.ENCHANTER,
    "Karthus": ChampionClass.CONTROL_MAGE,
    "Kassadin": ChampionClass.MAGIC_ASSASSIN,
    "Katarina": ChampionClass.MAGIC_ASSASSIN,
    "Kayle": ChampionClass.HYPER_CARRY,
    "Kayn": ChampionClass.DIVER,
    "Kennen": ChampionClass.CONTROL_MAGE,
    "Kha'Zix": ChampionClass.PHYSICAL_ASSASSIN,
    "Kindred": ChampionClass.EARLY_AD_CARRY,
    "Kled": ChampionClass.BRUISER,
    "Kog'Maw": ChampionClass.HYPER_CARRY,
    "LeBlanc": ChampionClass.PICK_MAGE,
    "Lee Sin": ChampionClass.DIVER,
    "Leona": ChampionClass.VANGUARD,
    "Lillia": ChampionClass.BATTLE_MAGE,
    "Lissandra": ChampionClass.PICK_MAGE,
    "Lucian": ChampionClass.EARLY_AD_CARRY,
    "Lulu": ChampionClass.ENCHANTER,
    "Lux": ChampionClass.PICK_MAGE,
    "Malphite": ChampionClass.VANGUARD,
    "Malzahar": ChampionClass.CONTROL_MAGE,
    "Maokai": ChampionClass.WARDEN,
    "Master Yi": ChampionClass.MELEE_AD_CARRY,
    "Miss Fortune": ChampionClass.EARLY_AD_CARRY,
    "Wukong": ChampionClass.BRUISER,
    "Mordekaiser": ChampionClass.BATTLE_MAGE,
    "Morgana": ChampionClass.PICK_MAGE,
    "Nami": ChampionClass.ENCHANTER,
    "Nasus": ChampionClass.JUGGERNAUT,
    "Nautilus": ChampionClass.VANGUARD,
    "Neeko": ChampionClass.PICK_MAGE,
    "Nidalee": ChampionClass.POKE_MAGE,
    "Nocturne": ChampionClass.DIVER,
    "Nunu & Willump": ChampionClass.VANGUARD,
    "Olaf": ChampionClass.BRUISER,
    "Orianna": ChampionClass.CONTROL_MAGE,
    "Ornn": ChampionClass.VANGUARD,
    "Pantheon": ChampionClass.PHYSICAL_ASSASSIN,
    "Poppy": ChampionClass.WARDEN,
    "Pyke": ChampionClass.PHYSICAL_ASSASSIN,
    "Qiyana": ChampionClass.PHYSICAL_ASSASSIN,
    "Quinn": ChampionClass.EARLY_AD_CARRY,
    "Rakan": ChampionClass.VANGUARD,
    "Rammus": ChampionClass.VANGUARD,
    "Rek'Sai": ChampionClass.PHYSICAL_ASSASSIN,
    "Rell": ChampionClass.VANGUARD,
    "Renata Glasc": ChampionClass.ENCHANTER,
    "Renekton": ChampionClass.BRUISER,
    "Rengar": ChampionClass.PHYSICAL_ASSASSIN,
    "Riven": ChampionClass.BRUISER,
    "Rumble": ChampionClass.BATTLE_MAGE,
    "Ryze": ChampionClass.CONTROL_MAGE,
    "Samira": ChampionClass.MELEE_AD_CARRY,
    "Sejuani": ChampionClass.VANGUARD,
    "Senna": ChampionClass.HYPER_CARRY,
    "Seraphine": ChampionClass.ENCHANTER,
    "Sett": ChampionClass.BRUISER,
    "Shaco": ChampionClass.PHYSICAL_ASSASSIN,
    "Shen": ChampionClass.VANGUARD,
    "Shyvana": ChampionClass.BATTLE_MAGE,
    "Singed": ChampionClass.BATTLE_MAGE,
    "Sion": ChampionClass.VANGUARD,
    "Sivir": ChampionClass.AD_CASTER,
    "Skarner": ChampionClass.VANGUARD,
    "Sona": ChampionClass.ENCHANTER,
    "Soraka": ChampionClass.ENCHANTER,
    "Swain": ChampionClass.BATTLE_MAGE,
    "Sylas": ChampionClass.MAGIC_ASSASSIN,
    "Syndra": ChampionClass.PICK_MAGE,
    "Tahm Kench": ChampionClass.BRUISER,
    "Taliyah": ChampionClass.CONTROL_MAGE,
    "Talon": ChampionClass.PHYSICAL_ASSASSIN,
    "Taric": ChampionClass.WARDEN,
    "Teemo": ChampionClass.BATTLE_MAGE,
    "Thresh": ChampionClass.WARDEN,
    "Tristana": ChampionClass.EARLY_AD_CARRY,
    "Trundle": ChampionClass.BRUISER,
    "Tryndamere": ChampionClass.MELEE_AD_CARRY,
    "Twisted Fate": ChampionClass.PICK_MAGE,
    "Twitch": ChampionClass.HYPER_CARRY,
    "Udyr": ChampionClass.BRUISER,
    "Urgot": ChampionClass.JUGGERNAUT,
    "Varus": ChampionClass.AD_CASTER,
    "Vayne": ChampionClass.HYPER_CARRY,
    "Veigar": ChampionClass.HYPER_CARRY,
    "Vel'Koz": ChampionClass.POKE_MAGE,
    "Vex": ChampionClass.CONTROL_MAGE,
    "Vi": ChampionClass.DIVER,
    "Viego": ChampionClass.MELEE_AD_CARRY,
    "Viktor": ChampionClass.CONTROL_MAGE,
    "Vladimir": ChampionClass.BATTLE_MAGE,
    "Volibear": ChampionClass.BRUISER,
    "Warwick": ChampionClass.BRUISER,
    "Xayah": ChampionClass.HYPER_CARRY,
    "Xerath": ChampionClass.POKE_MAGE,
    "Xin Zhao": ChampionClass.BRUISER,
    "Yasuo": ChampionClass.MELEE_AD_CARRY,
    "Yone": ChampionClass.MELEE_AD_CARRY,
    "Yorick": ChampionClass.JUGGERNAUT,
    "Yuumi": ChampionClass.ENCHANTER,
    "Zac": ChampionClass.VANGUARD,
    "Zed": ChampionClass.PHYSICAL_ASSASSIN,
    "Zeri": ChampionClass.HYPER_CARRY,
    "Ziggs": ChampionClass.POKE_MAGE,
    "Zilean": ChampionClass.ENCHANTER,
    "Zoe": ChampionClass.POKE_MAGE,
    "Zyra": ChampionClass.CONTROL_MAGE,
}
